<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="css/error.css" rel="stylesheet">
    <title>The Barn Error</title>
</head>
<body>
<div style="align-content: center; margin: auto">
<h1>Upszika</h1>
<br>
<p>Valami hiba történt</p>
<br>
<a href="/"><button type="button" class="btn btn-outline-success">Vissza a főoldalra</button></a>
</div>
</body>
</html>